### PR TITLE
refresh_slots fix dns resolve delay

### PR DESCRIPTION
**Pull request by alexander-shabanov**
Temp fix: Change 'addresses to connections' (specifically get_socket_addrs) to be sequential instead of concurrent in order to workaround DNS query throttling

### CODE REVIEW

**Comment by nihohit** [comment]
why does DNS query throttling make it slower than sequential attempts?

**Comment by barshaul** [comment]
@nihohit We haven't dived deep into why it takes longer - it look like it's due to DNS throttling.
ATM we see that it takes 5 seconds when we run it concurrently VS ~500 milliseconds when we run it sequentially.
We should RC it but at the moment lets have this fix and work to solve it later.
@alexander-shabanov have you opened an issue for this?

**Comment by barshaul** [comment]
@alexander-shabanov Can you test this change with a small cluster - lets say 3 shards, master&replica in each, to see what's the impact in terms of time to create the client?

**Comment by alexander-shabanov** [comment]
@nihohit  @barshaul I have submitted an issue [make DNS resolution and creation of connections to be concurrent](https://github.com/aws/babushka/issues/550) to follow up this fix.

**Comment by barshaul** [comment]
@alexander-shabanov Please pull latest changes

**Comment by alexander-shabanov** [comment]
@barshaul Pulled latest changes

**Review by barshaul — APPROVED** [review]

**Pull request merged**
